<a href="https://colab.research.google.com/github/maheksa1234/Online-Workshop-Applications-of-Python-programming/blob/master/workshop_Day3_session2_eg2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas Examples

#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8..... 10]) 
print(ds)
print(type(ds))


SyntaxError: ignored

#Write a Pandas program to convert a Panda module Series to Python list and its type.

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


##Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool


##Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


##Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


##Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']


In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


## Write a Pandas program to convert a given Series to an array.

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.

In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [ ]:

import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)


#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv


In [ ]:

import pandas as pd
import numpy as np
df = pd.read_csv(io.BytesIO(uploded['movie_metadata.csv']))
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)






sorted by country                                                              
   reviews language country  rating  budget  year

2        2    hindi     ast       4  9 lack  2019

0        4      eng     end       4  7 lack  2017

5        3      eng     end       4  9 lack  2015

1        3  kannada     ind       4   8lack  2018

4        4    telgu  russia       4  8 lack  2013

3        5    tamil     usa       4   7lack  2012

#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)


Columns of the DataFrame:
Index(['reviews', 'language', 'country', 'budget', 'rating', 'year', 'actor'], dtype='object')

#Write a Pandas program to display the first 10 rows of the DataFrame

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

#Numpy Examples

#Write a NumPy program to generate five random numbers from the normal distribution.


In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[-1.30500851  0.13080068  0.26732515 -0.98815713  1.66135134]


##Write a NumPy program to generate six random integers between 10 and 30

In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[27 21 10 14 15 21]


#Write a NumPy program to create a 3x3x3 array with random values.

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.78548344 0.11349448 0.76720804]
  [0.20834503 0.26499293 0.47987042]
  [0.96328075 0.21899681 0.25433807]]

 [[0.82131092 0.08497246 0.64819235]
  [0.89549026 0.47709138 0.5161136 ]
  [0.53463504 0.92034199 0.431229  ]]

 [[0.44576978 0.05781268 0.19205498]
  [0.95440773 0.13260111 0.542564  ]
  [0.15584895 0.06917661 0.36034799]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.44973373 0.19199676 0.16646911 0.91695134 0.25495747]
 [0.33405782 0.23236684 0.07989763 0.68374724 0.41679252]
 [0.04706742 0.40462155 0.75987543 0.49605023 0.29556583]
 [0.33353022 0.76228473 0.29515978 0.16551517 0.23205446]
 [0.9649939  0.4120335  0.49368482 0.40733415 0.07616455]]
Minimum and Maximum Values:
0.04706741880682419 0.9649938981373596


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)



Original array: 
[[0.38972554 0.78327615 0.89851064 0.54516395]
 [0.97197472 0.85417461 0.90107223 0.30778184]
 [0.80597149 0.78819981 0.8342415  0.89562261]
 [0.56260728 0.19142422 0.9892014  0.92662156]
 [0.10914865 0.31128933 0.49751521 0.08252787]
 [0.27805783 0.50093866 0.98560383 0.64022256]
 [0.27214583 0.37037686 0.26150952 0.95154491]
 [0.83168775 0.47896681 0.13836158 0.46415452]
 [0.00370333 0.35261528 0.95321769 0.84543396]
 [0.54358941 0.77369353 0.64867431 0.02897155]]
First 5 rows of the above array:
[[0.38972554 0.78327615 0.89851064 0.54516395]
 [0.97197472 0.85417461 0.90107223 0.30778184]
 [0.80597149 0.78819981 0.8342415  0.89562261]
 [0.56260728 0.19142422 0.9892014  0.92662156]
 [0.10914865 0.31128933 0.49751521 0.08252787]]
First 3 columns of the above array:
[[0.38972554 0.78327615 0.89851064 0.54516395]
 [0.97197472 0.85417461 0.90107223 0.30778184]
 [0.80597149 0.78819981 0.8342415  0.89562261]
 [0.56260728 0.19142422 0.9892014  0.92662156]
 [0.10914865 0.3112

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [ ]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[0 6 1 5 7 2 4 3 8 9]
Same result using permutation():
[6 8 4 9 1 0 3 7 5 2]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)


[6 4 2 9 5 8 7 1 3 0]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[4 5 8 3 7 1 2 0 9 6]
[0 1 2 3 4 5 6 7 8 9]
