<a href="https://colab.research.google.com/github/maheksa1234/Online-Workshop-Applications-of-Python-programming/blob/master/workshop_Day3_session2_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas and Numpy Exercise 20 Questions
#Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10000

In [ ]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)


0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
l=([i for i in range(1000,20000) if i%5==0])
ds = pd.Series(l) 
print(ds)

0        1000
1        1005
2        1010
3        1015
4        1020
        ...  
3795    19975
3796    19980
3797    19985
3798    19990
3799    19995
Length: 3800, dtype: int64


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
l1=([i for i in range(0,101) if i%2==0])
ds1 = pd.Series(l1)
l2=([i for i in range(0,100) if i%2!=0])
ds2 = pd.Series(l2)
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0       1.0
1       5.0
2       9.0
3      13.0
4      17.0
5      21.0
6      25.0
7      29.0
8      33.0
9      37.0
10     41.0
11     45.0
12     49.0
13     53.0
14     57.0
15     61.0
16     65.0
17     69.0
18     73.0
19     77.0
20     81.0
21     85.0
22     89.0
23     93.0
24     97.0
25    101.0
26    105.0
27    109.0
28    113.0
29    117.0
30    121.0
31    125.0
32    129.0
33    133.0
34    137.0
35    141.0
36    145.0
37    149.0
38    153.0
39    157.0
40    161.0
41    165.0
42    169.0
43    173.0
44    177.0
45    181.0
46    185.0
47    189.0
48    193.0
49    197.0
50      NaN
dtype: float64
Subtract two Series:
0    -1.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5    -1.0
6    -1.0
7    -1.0
8    -1.0
9    -1.0
10   -1.0
11   -1.0
12   -1.0
13   -1.0
14   -1.0
15   -1.0
16   -1.0
17   -1.0
18   -1.0
19   -1.0
20   -1.0
21   -1.0
22   -1.0
23   -1.0
24   -1.0
25   -1.0
26   -1.0
27   -1.0
28   -1.0
29   -1.0
30   -1.0
31   -1.0
32   -1.0
33   -

#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series. Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [ ]:
import pandas as pd
l1=([i for i in range(0,1000) if i%7==0])
d1 = pd.Series(l1)
l2=([i for i in range(0,1000) if i%11==0])
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   True
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87   

#Write a Pandas program to convert a NumPy array to a Pandas series. Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
np_array = np.array(l1)
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000]
Converted Pandas series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


#Write a Pandas program to convert a given Series to an array. Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#Write a Pandas program to sort a given Series. Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


#Write a Pandas program to create a subsets of a given series based on value and condition. ample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
s = pd.Series(l1)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=7
new_s = s[s%n==0]
print(new_s)
n=5
new_s = s[s%n==0]
print(new_s)

Original Data Series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64

Subset of the above Data Series:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


#Write a Pandas program to get the elements of an array values into column-wise. Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

exam_data  = {'name': ['mahek', 'Danish', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a      mahek   12.5         1     yes
b     Danish    9.0         3      no
c  Katherine   16.5         2     yes


In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [42]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [47]:
downloaded = drive.CreateFile({'id':'1WoQm1twpMmaX9miO0KPVeugSWAMeU26O'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv')

In [48]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

   color  director_name  ...  movie_facebook_likes  Unnamed: 28
0  Color  James Cameron  ...                 33000          NaN

[1 rows x 29 columns]


#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [49]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
color                                                                    Color
director_name                                                Christopher Nolan
num_critic_for_reviews                                                     813
duration                                                                   164
director_facebook_likes                                                  22000
actor_3_facebook_likes                                                   23000
actor_2_name                                                    Christian Bale
actor_1_facebook_likes                                                   27000
gross                                                              4.48131e+08
genres                                                         Action|Thriller
actor_1_name                                                         Tom Hardy
movie_title                                             The Dark Knight Rises 
num_voted_users       

#Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields

In [54]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[[]]
print("Details of title and genres:")
print(result)

Details of title and genres:
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[5043 rows x 0 columns]


#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)

[[0.40391001 0.18349205 0.23515526 0.93752209]
 [0.35623378 0.61340812 0.6708745  0.19991775]
 [0.52383552 0.22268757 0.9144551  0.20347416]
 [0.48491559 0.37277553 0.60642242 0.7441536 ]]
2nd and 3rd rows of the above array:
[[0.35623378 0.61340812 0.6708745  0.19991775]
 [0.52383552 0.22268757 0.9144551  0.20347416]]


#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.9508366  0.28295214 0.11575012 0.21036535 0.67468667 0.64183475
  0.56923262 0.86564129 0.80223335 0.13726711]
 [0.19559462 0.60608823 0.8330576  0.68921489 0.71117753 0.5481053
  0.97300338 0.33482916 0.43266545 0.27700984]
 [0.09411515 0.19876074 0.49825567 0.77027688 0.55950304 0.95857633
  0.32278872 0.74727847 0.61461798 0.31099048]
 [0.14100755 0.56663756 0.09847456 0.6519754  0.04562476 0.17758103
  0.11984839 0.47091422 0.55626571 0.79729755]
 [0.81864679 0.46818328 0.82881483 0.17693613 0.68784349 0.33613724
  0.66963958 0.18687703 0.69206239 0.28441192]
 [0.80492928 0.11650548 0.48779603 0.75738073 0.58264539 0.88952528
  0.43155925 0.51196102 0.56143284 0.9433168 ]
 [0.69066374 0.42292978 0.90187303 0.68654042 0.88531345 0.43710478
  0.27808349 0.15904889 0.66165107 0.51804977]
 [0.64565515 0.57917335 0.94615861 0.68012002 0.96692108 0.80185208
  0.00130527 0.07197414 0.96110895 0.42140008]
 [0.54822217 0.03326279 0.3852361  0.60984686 0.02915538 0.951590

#Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[225 191 119 253 135 215 240 133]


#Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[10 13 17 11  7  4 16 14  0  5  2  3 18  6 15  1 19  9 12  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
